climbtracker-dev-postgresql:
  container_name: climbtracker-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/climbtracker/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=climbtracker
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
